import localFont from "next/font/local";
import "./globals.css";
import Navbar from "./components/Navbar";
import Topbar from "./components/TopBar";
import Footer from "./components/Footer";

// Cargar fuentes locales
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});

const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="es">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="flex flex-col h-screen">
          {/* Topbar */}
          <Topbar />

          <div className="flex flex-1">
            {/* Barra de navegación fija en el lateral izquierdo */}
            <Navbar />
            
            {/* Contenido principal que ocupa el resto de la pantalla */}
            <main className="ml-64 p-4 flex-1 overflow-y-auto">
              {children}
            </main>
          </div>
          <Footer/>
        </div>
      </body>
    </html>
  );
}
